go-oauth2/oauth2

.gitignore
example/server/main.go
generates/access.go
generates/authorize.go
manage/manage_test.go
manage/manager.go
server/server_test.go
store/token.go
store/token_test.go

* Use [buntdb](https://github.com/tidwall/buntdb) provide token storage

Token storage optimization

---

example/client/client.go
server/server.go

This way it is easy to see if the server is still complying to the spec.
Also remove the check for client_id from server.go, which is not needed
any more now that the server uses basic HTTP auth to authenticate the
client.
ref. #35

Use golang.org/x/oauth2 in client impl

---

generate.go
manage/manager.go

Changes:
- Added a field for TokenInfo to the GenerateBasic struct
- Addedthe actual TokenInfo to every creation of GenerateBasic
Reason:
Since an very own implementation of TokenInfo can be set into the manager it makes
much more sense to have that at hand while generating the Auth, Access and RefreshToken.
With this change an issuing of signed JWT is possible.

TokenInfo in GenerateBasic

---

manage/manager.go

Because the oauth server need to get scope info when invoke AuthorizeGenerate and AccessGenerate

Set TokenInfo before Invoke AuthorizeGenerate

---

generates/access.go
generates/authorize.go
store/token.go

A backwards breaking change has been commit to master in the https://github.com/satori/go.uuid dependency, which has resulted in `gopkg.in/oauth2.v3` no longer being able to compile.
This changes fix that issue in old-style way as described in https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c

Fix uuid generation

---

manage/manager.go

Use the same code from this commit a305d018
Fixes #51

Initialize TokenInfo before invoking AccessGenerate.Token

---

README.md

The current implementation of MySQL datastore only provides the token store implementation, but client store. 
I created a new repository for implementing both token and client store with some inspiration from postgres store implementation in [`https://github.com/vgarvardt/go-oauth2-pg`](https://github.com/vgarvardt/go-oauth2-pg). 
Please check [`github.com/imrenagi/go-oauth2-mysql`](https://github.com/imrenagi/go-oauth2-mysql)

Add link to new implementation of token and client store for mysql db

---

const.go

There is no need to confirm the value of a type, and it makes it impossible to add additional ResponseType like "id_token"
https://play.golang.org/p/kpd23-n4oQ3 
I'm trying to use this package to host a OIDC server, but the response_type validation always fails as every other 
```
[ResponseType].String() == ""
```

Removed checks done on ResponseType String()

---

generate.go
generates/access.go
generates/access_test.go
generates/authorize.go
generates/authorize_test.go
generates/jwt_access.go
generates/jwt_access_test.go
manage.go
manage/manage_test.go
manage/manager.go
server/server.go
store.go
store/client.go
store/client_test.go
store/token.go
store/token_test.go

Context support is a must-have these days. The buntdb doesn't seem to support context but other databases do, such as Redis, MySQL, etc.
This diff adds context support.
Test plan:
1. Unit tests are passing
2. Manually compiled `example` server and client and run manual test
Original issue: #65

add context support

---

manage/manager.go
model.go

It is not secure to use plain passwords and a way to handle custom password hashes is a must.
This diff would allow something like this to work with bcrypt and other hashing methods:
```go
import "golang.org/x/crypto/bcrypt"
type MyClient struct {
models.Client
}
func (c *MyClient) VerifyPassword(password string) bool {
err := bcrypt.CompareHashAndPassword([]byte(password), []byte(c.GetSecret()))
return err == nil
}
```
Closes #108

Allows client to use custom password verification

---

manage/manager.go

See #156 
Essentially this PR does change the condition for the secret check. Before it would only see if the secret was submitted, now it sees if the client has a secret.

Fix client secret not being checked

---

server/handler.go
server/server.go
server/server_config.go

I hope authorization will invaild if user revoke or change password . So I want to check refresh token is vaild when refershing.  I add a handler named Refreshing vaildationHandler help me do it

add RefreshingValidationHandler when refershing token

---

server/server.go

ForcePKCE config parameter should only be taken into account for Authorization Code flow. Currently other flows (Client Credentials, etc) will fail token creation if ForcePKCE is set to true.
Fixes https://github.com/go-oauth2/oauth2/issues/172

Check PCKE only for Authorization code flow

---

.gitignore
manage/manager.go
server/server.go

This PR fixed the client secret check using the same approach for authorization. It also fixed the compilation error on server.go line 243.

fixed the bug to compare client secrets when refreshing token

---

server/server.go

fix server.go:243:6: no new variables on left side of :=

---

server/server.go

github.com\go-oauth2\oauth2\v4@v4.4.0\server\server.go:243:6: no new variables on left side of :=
relate issue: #194

fix: github.com\go-oauth2\oauth2\v4@v4.4.0\server\server.go:243:6: no new variables on left side of :=

---

server/handler.go
server/server.go
server/server_config.go

```
func (s *Server) token(w http.ResponseWriter, data map[string]interface{}, header http.Header, statusCode ...int) error {
if fn := s.ResponseTokenHandler; fn != nil {
return fn(w, data, header, statusCode...)
}
```

add ResponseTokenHandler when respose token to the browser

---

manage/manage_test.go
manage/manager.go

to meet the rfc6749 guidelines.
https://datatracker.ietf.org/doc/html/rfc6749#section-6
rfc6749 section 6 mentions only "refresh_token" and "grant_type" are REQUIRED,
while the previous implementation requires "client_id" and "client_secret".

modifed the implementation of the refresh token process

---

server/server.go

If invalid code challenge method (for example, `code_challenge_method=invalid`) is specified in Authorize request, it was not checked since `ccm.String()` returned empty string for unknown methods - the request was allowed to pass through.
This fix checks for empty code challenge method thus enabling the verification for invalid code challenge methods.

Handle invalid code challenge methods

---

example/server/server.go
server/handler.go
server/server.go
server/server_test.go

Adds `context.Context` as the first parameter of `server.PasswordAuthorizationHandler`.  This could be used for adding contextual information and using it later.

Added context to PasswordAuthroizationHandler (#173)

---

server/handler.go
server/server.go
server/server_config.go

This PR adds a mechanism that can be used to override the default error handling behavior implemented by `s.redirectError`. The error handler of this mechanism is defined as `func(rw http.ResponseWriter, req *server.AuthorizeRequest, error error) error`, and can be enabled by passing a non-nil function to `SetPreRedirectErrorHandler`.

Added an error handler that is invoked before s.redirectError

---

README.md

Hi,
I've written and implementation of `oauth2.TokenStore` at [clowre/go-oauth2-hazelcast](https://github.com/clowre/go-oauth2-hazelcast) that utilizes [Hazelcast](https://hazelcast.com/) for storage.
I'd like to get a code review of the package and see if it can be linked in this repository's README.

Added Hazelcast Token store to README

---

example/server/server.go
server/handler.go
server/server.go
server/server_test.go

Just add `clientID` in `PasswordAuthorizationHandler` if we need to customize password authorization per client.

Per client authorization

---

manage/manager.go
model.go
models/client.go
server/server_test.go

- denying client credentials grant if client is public
- adjusting tests to make different clients based on whether or not they are public
- this will allow for using public grants like authorisation code flow with client_secret not set on client and Public set to true
- if libraries implement this and dont want to care about it they can just return false for IsPublic (i forked go-oauth2-pg and changed it to contain public field in db)

Introducing public field to client models

---

generates/jwt_access.go
generates/jwt_access_test.go

This PR updates the JWT implementation to use v5 to fix the vulnerability GO-2025-3553 related to excessive memory allocation during header parsing.
Changes:
1. Updated to JWT v5 to fix the vulnerability
2. Maintained backward compatibility by:
- Using `RegisteredClaims` which has the same fields as `StandardClaims`
- Using `jwt.ClaimStrings` for audience which is compatible with both string and array formats
- Keeping the same method signatures and struct names
3. Updated the tests to work with JWT v5
4. Updated go.mod to use the latest JWT v5 version
All tests are passing:
- `github.com/go-oauth2/oauth2/v4`: ✅
- `github.com/go-oauth2/oauth2/v4/generates`: ✅
- `github.com/go-oauth2/oauth2/v4/manage`: ✅
- `github.com/go-oauth2/oauth2/v4/server`: ✅
- `github.com/go-oauth2/oauth2/v4/store`: …

chore: update to JWT v5 to fix vulnerability GO-2025-3553

---

server/handler.go
server/handler_test.go
server/server.go
server/server_config.go

So we use this library but now we want to store the tokens in HttpOnly cookies. Like this when we want to get a new access token with the refresh token we have to get the refresh token from the cookie and our client can't include it in the request body.
The default functionality is the same as before and I have included a new handler for the cookie too. I have included some unit tests too.

Refresh and Access token resolve handler

---

go.mod
go.sum

- Seems the JWT v5 dependency actually requires `1.21`
- `go: github.com/golang-jwt/jwt/v5@v5.3.0 requires go@1.21, but 1.13 is requested`

chore: run `go mod tidy` specifying Go 1.21 to resolve CVE
